## Agenda

- **2-D arrays (Matrices)**✅
    - `reshape()`✅
    - Transpose✅
    - Converting Matrix back to Vector - `flatten()`✅

- **Introduction to use case**


- **Indexing and Slicing on 2D** 
    - Indexing✅

    - Slicing✅

    - Masking (Fancy Indexing)✅


- **Universal Functions (ufunc) on 2D**
    - Aggregate Function/ Reduction functions - `sum()`, `mean()`, `min()`, `max()`✅
    
    - Axis argument✅

    - Logical Operations✅
    
    - Sorting function - `sort()`, `argsort()`✅

       
 - **Use Case: Fitness Data analysis**
    - Loading data set and EDA using numpy
    - `np.argmax()`

## **2-D arrays (Matrices)**

###  Transpose

In [ ]:
a=np.arange(1,13)
a=a.reshape((3,4))
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
a.transpose()

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [ ]:
a.T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [ ]:
b=np.arange(1,13)
c=b.reshape((1,12))


In [ ]:
b

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
c

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [ ]:
b.shape

(12,)

In [ ]:
c.shape

(1, 12)

In [ ]:
c.T

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

In [ ]:
b.T

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

### `flatten()`

In [ ]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
# nd array to 1d array

In [ ]:
a.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
a.reshape((-1,))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

## **Indexing and Slicing on 2D**

### Indexing

In [ ]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
# method1

a[1][1]

6

In [ ]:
# method2  # recommended
a[1,1]

6

In [ ]:
a[-1,-2]

11

In [ ]:
a[2,-2]

11

In [ ]:
a[[1,2,2],[1,2,3]]

array([ 6, 11, 12])

In [ ]:
a[[0,2,2],[2,3,0]]

array([ 3, 12,  9])

In [ ]:
a[[-2,-3,-1,-2],[-3,-1,-3,-1]]

array([ 6,  4, 10,  8])

### Slicing

In [ ]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
a[::,::]

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
a[:2:1,::]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
a[:2:1,1::2]

array([[2, 4],
       [6, 8]])

In [ ]:
a[1::-1,2::1]

array([[7, 8],
       [3, 4]])

In [ ]:
a[1::-1,2::-1]

array([[7, 6, 5],
       [3, 2, 1]])

In [ ]:
a[0:2:2,-2::-2]

array([[3, 1]])

In [ ]:
# a[0:2:2,-2:-1:-2]

In [ ]:
a[::-2,:-4:-3]

array([[12],
       [ 4]])

### Masking

In [ ]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
a+10

array([[11, 12, 13, 14],
       [15, 16, 17, 18],
       [19, 20, 21, 22]])

In [ ]:
a<10

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True, False, False, False]])

In [ ]:
a[a<10]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a[a>100]

array([], dtype=int64)

In [ ]:
a[a<100]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
a[(a%2==0)|(a%5==0)]

array([ 2,  4,  5,  6,  8, 10, 12])

In [ ]:
a[(a%2==0)&(a%5==0)]

array([10])

## **Universal Functions (ufunc) on 2D**

### `sum()`, `mean()`, `min()`, `max()`

In [ ]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
np.mean(a)

6.5

In [ ]:
np.max(a)

12

In [ ]:
np.min(a)

1

In [ ]:
np.sum(a)

78

### Axis argument

In [ ]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
np.sum(a,axis=0)

array([15, 18, 21, 24])

In [ ]:
np.sum(a,axis=1)

array([10, 26, 42])

In [ ]:
np.sum(a,axis=-1)

array([10, 26, 42])

In [ ]:
np.sum(a,axis=-2)

array([15, 18, 21, 24])

In [ ]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
np.min(a,axis=0)

array([1, 2, 3, 4])

In [ ]:
np.min(a,axis=-2)

array([1, 2, 3, 4])

In [ ]:
np.min(a,axis=1)

array([1, 5, 9])

In [ ]:
np.min(a,axis=-1)

array([1, 5, 9])

In [ ]:
a=np.arange(1,13)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
# np.sum(a,axis=1)

In [ ]:
np.sum(a,axis=0)

78

In [ ]:
np.sum(a)

78

### Logical Operations

In [ ]:
a

array([[ 10,   2,  99],
       [100,   4,  21],
       [ 32,   5,  12],
       [  9,  57,  45]])

In [ ]:
a<10

array([[False,  True, False],
       [False,  True, False],
       [False,  True, False],
       [ True, False, False]])

In [ ]:
a[a<10]

array([2, 4, 5, 9])

In [ ]:
b=np.arange(1,13).reshape((4,3))
b

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
a

array([[ 10,   2,  99],
       [100,   4,  21],
       [ 32,   5,  12],
       [  9,  57,  45]])

In [ ]:
a<b

array([[False, False, False],
       [False,  True, False],
       [False,  True, False],
       [ True, False, False]])

In [ ]:
np.all(a<b)

False

In [ ]:
np.any(a<b)

True

### Sorting function - `sort()`, `argsort()`

In [ ]:
a=np.array([[ 10,   2,  99],
       [100,   4,  21],
       [ 32,   5,  12],
       [  9,  57,  45]])

In [ ]:
a

array([[ 10,   2,  99],
       [100,   4,  21],
       [ 32,   5,  12],
       [  9,  57,  45]])

In [ ]:
np.sort(a,axis=0)

array([[  9,   2,  12],
       [ 10,   4,  21],
       [ 32,   5,  45],
       [100,  57,  99]])

In [ ]:
# np.sort(a,axis=-2)

In [ ]:
np.sort(a,axis=1)

array([[  2,  10,  99],
       [  4,  21, 100],
       [  5,  12,  32],
       [  9,  45,  57]])

In [ ]:
# np.sort(a,axis=-1)

In [ ]:
a

array([[ 10,   2,  99],
       [100,   4,  21],
       [ 32,   5,  12],
       [  9,  57,  45]])

In [ ]:
np.sort(a)

array([[  2,  10,  99],
       [  4,  21, 100],
       [  5,  12,  32],
       [  9,  45,  57]])

In [ ]:
# 1D np array

In [ ]:
a=np.array([2,7,3,9,4,1,6])
a

array([2, 7, 3, 9, 4, 1, 6, 7])

In [ ]:
#method 1
np.sort(a)


array([1, 2, 3, 4, 6, 7, 7, 9])

In [ ]:
a

array([2, 7, 3, 9, 4, 1, 6, 7])

In [ ]:
# method2 
a.sort()

In [ ]:
a

array([1, 2, 3, 4, 6, 7, 7, 9])

In [ ]:
# np.argsort()

In [ ]:
a=np.array([2,7,3,9,4,1,6])
a

array([2, 7, 3, 9, 4, 1, 6])

In [ ]:
np.sort(a)

array([1, 2, 3, 4, 6, 7, 9])

In [ ]:
np.argsort(a)

array([5, 0, 2, 4, 6, 1, 3])

In [ ]:
np.argmax(a)

3

In [ ]:
np.argmin(a)

5

### `np.unique()`

## **Use Case: Fitness Data analysis**