## Agenda

    
- **Dimension Expansion and Reduction**✅
    - `np.expand_dims()`✅
    - `np.newaxis`✅
    - `np.sqeeze()`✅
    
    
    
- **Shallow vs Deep Copy**✅
    - `view()`✅
    - `copy()`✅
    - `copy.deepcopy()`✅

    
    
- **Array splitting and Merging**✅
    - Splitting arrays - `split()`, `hsplit()`, `vsplit()`✅
    - Merging Arrays - `hstack()`, `vstack()`✅
    


## **Dimension Expansion and Reduction**

### `np.expand_dims()`

In [1]:
a=np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [2]:
a.ndim

1

In [8]:
b=a.reshape((2,3))
b

array([[0, 1, 2],
       [3, 4, 5]])

In [9]:
b.shape

(2, 3)

In [10]:
b.ndim

2

In [12]:
c=b.reshape((2,3,1,1,1,1,1,1,1))
c

array([[[[[[[[[0]]]]]]],






        [[[[[[[1]]]]]]],






        [[[[[[[2]]]]]]]],







       [[[[[[[[3]]]]]]],






        [[[[[[[4]]]]]]],






        [[[[[[[5]]]]]]]]])

In [13]:
len(c)

2

In [14]:
c.ndim

9

In [15]:
a

array([0, 1, 2, 3, 4, 5])

In [17]:
a.ndim,a.shape

(1, (6,))

In [18]:
np.expand_dims(a,axis=0).shape

(1, 6)

In [19]:
np.expand_dims(a,axis=1).shape

(6, 1)

In [20]:
a=np.arange(1,13).reshape((3,4))
a.shape,a.ndim


((3, 4), 2)

In [22]:
np.expand_dims(a,axis=0).shape

(1, 3, 4)

In [23]:
np.expand_dims(a,axis=1).shape

(3, 1, 4)

In [24]:
np.expand_dims(a,axis=2).shape

(3, 4, 1)

### `np.newaxis`

In [25]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [26]:
a.shape,a.ndim

((3, 4), 2)

In [27]:
a=np.arange(6)
a.shape,a.ndim

((6,), 1)

In [29]:
a[:,np.newaxis].shape

(6, 1)

In [30]:
a[np.newaxis,:].shape

(1, 6)

In [31]:
a=np.arange(1,13).reshape((3,4))
a.shape,a.ndim

((3, 4), 2)

In [32]:
a[:,np.newaxis,:].shape

(3, 1, 4)

In [33]:
a[:,np.newaxis].shape

(3, 1, 4)

In [34]:
a[np.newaxis,:,:].shape

(1, 3, 4)

In [35]:
a[:,:,np.newaxis].shape

(3, 4, 1)

In [36]:
a[:,:,np.newaxis,np.newaxis,np.newaxis,np.newaxis].shape

(3, 4, 1, 1, 1, 1)

In [37]:
a[:,np.newaxis,:,np.newaxis,np.newaxis,np.newaxis].shape

(3, 1, 4, 1, 1, 1)

In [38]:
a[:,np.newaxis,np.newaxis,np.newaxis,np.newaxis].shape

(3, 1, 1, 1, 1, 4)

In [39]:
a[:,None,None,None,None,:].shape

(3, 1, 1, 1, 1, 4)

In [40]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [41]:
a[:,None,None,None,None,:]

array([[[[[[ 1,  2,  3,  4]]]]],




       [[[[[ 5,  6,  7,  8]]]]],




       [[[[[ 9, 10, 11, 12]]]]]])

### `np.sqeeze()`

In [42]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [46]:
c=a.reshape((2,1,2,1,3))
c.shape,c.ndim


((2, 1, 2, 1, 3), 5)

In [47]:
np.squeeze(c).shape

(2, 2, 3)

In [49]:
np.squeeze(c,axis=1).shape

(2, 2, 1, 3)

In [50]:
np.squeeze(c,axis=3).shape

(2, 1, 2, 3)

In [52]:
# np.squeeze(c,axis=4).shape

## **Shallow vs Deep Copy**

In [87]:
a=np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [88]:
b=a

In [89]:
np.shares_memory(a,b)

True

In [55]:
b

array([1, 2, 3, 4])

In [56]:
a[0]=100
a

array([100,   2,   3,   4])

In [57]:
b

array([100,   2,   3,   4])

In [90]:
c=a.reshape((2,2))
c

array([[1, 2],
       [3, 4]])

In [91]:
np.shares_memory(a,c)

True

In [59]:
a[1]=200

In [60]:
a

array([100, 200,   3,   4])

In [61]:
b

array([100, 200,   3,   4])

In [62]:
c

array([[100, 200],
       [  3,   4]])

In [64]:
a[2:3]

array([3])

In [92]:
d=a[:]
d

array([1, 2, 3, 4])

In [93]:
np.shares_memory(a,d)

True

In [67]:
d[2:3]=300

In [68]:
d

array([100, 200, 300,   4])

In [69]:
a

array([100, 200, 300,   4])

In [94]:
e=np.array(a,dtype="float")
e

array([1., 2., 3., 4.])

In [95]:
np.shares_memory(a,e)

False

In [71]:
a

array([100, 200, 300,   4])

In [72]:
a[0]=200.0

In [73]:
a

array([200, 200, 300,   4])

In [74]:
e

array([100., 200., 300.,   4.])

In [75]:
a

array([200, 200, 300,   4])

In [96]:
f=a+0

In [97]:
np.shares_memory(a,f)

False

In [77]:
a

array([200, 200, 300,   4])

In [78]:
f

array([200, 200, 300,   4])

In [79]:
f[1]=1000

In [80]:
f

array([ 200, 1000,  300,    4])

In [81]:
a

array([200, 200, 300,   4])

In [98]:
g=a*1
g

array([1, 2, 3, 4])

In [99]:
np.shares_memory(a,g)

False

In [83]:
a

array([200, 200, 300,   4])

In [84]:
g[0]=2000

In [85]:
g

array([2000,  200,  300,    4])

In [86]:
a

array([200, 200, 300,   4])

In [101]:
a=np.arange(1,4)
a

array([1, 2, 3])

In [102]:
b=a

In [103]:
np.shares_memory(a,b)

True

In [104]:
d=a.copy()
d

array([1, 2, 3])

In [105]:
np.shares_memory(a,d)

False

In [106]:
a[0]=100

In [107]:
a

array([100,   2,   3])

In [108]:
d

array([1, 2, 3])

### Exception ( not to be remembered)

In [109]:
a=np.array([1,"m",[1,2,3]],dtype="object")
a

array([1, 'm', list([1, 2, 3])], dtype=object)

In [110]:
b=a.copy()
b

array([1, 'm', list([1, 2, 3])], dtype=object)

In [112]:
a[2][0]=100

In [113]:
a

array([1, 'm', list([100, 2, 3])], dtype=object)

In [114]:
b

array([1, 'm', list([100, 2, 3])], dtype=object)

In [115]:
import copy

In [116]:
c=copy.deepcopy(a)

In [117]:
c

array([1, 'm', list([100, 2, 3])], dtype=object)

In [119]:
a[2][1]=200

In [120]:
a

array([1, 'm', list([100, 200, 3])], dtype=object)

In [121]:
c

array([1, 'm', list([100, 2, 3])], dtype=object)

## **Array splitting and Merging**

### Splitting arrays

In [122]:
a=np.arange(1,13)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [123]:
np.split(a,3)

[array([1, 2, 3, 4]), array([5, 6, 7, 8]), array([ 9, 10, 11, 12])]

In [125]:
# np.split(a,5)

In [126]:
np.split(a,[3,5,7])

[array([1, 2, 3]), array([4, 5]), array([6, 7]), array([ 8,  9, 10, 11, 12])]

In [127]:
np.split(a,[3,5,3])

[array([1, 2, 3]),
 array([4, 5]),
 array([], dtype=int64),
 array([ 4,  5,  6,  7,  8,  9, 10, 11, 12])]

In [128]:
a=np.arange(1,13).reshape((3,4))
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [130]:
# np.split(a,2,axis=0)

In [131]:
np.split(a,3,axis=0)

[array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]]), array([[ 9, 10, 11, 12]])]

In [132]:
np.split(a,3)

[array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]]), array([[ 9, 10, 11, 12]])]

In [133]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [134]:
np.split(a,4,axis=1)

[array([[1],
        [5],
        [9]]),
 array([[ 2],
        [ 6],
        [10]]),
 array([[ 3],
        [ 7],
        [11]]),
 array([[ 4],
        [ 8],
        [12]])]

In [135]:
np.split(a,2,axis=1)

[array([[ 1,  2],
        [ 5,  6],
        [ 9, 10]]),
 array([[ 3,  4],
        [ 7,  8],
        [11, 12]])]

In [136]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [137]:
np.split(a,[1,2],axis=1)

[array([[1],
        [5],
        [9]]),
 array([[ 2],
        [ 6],
        [10]]),
 array([[ 3,  4],
        [ 7,  8],
        [11, 12]])]

In [138]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [139]:
np.split(a,[1,2],axis=0)

[array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]]), array([[ 9, 10, 11, 12]])]

In [140]:
np.split(a,[1],axis=0)

[array([[1, 2, 3, 4]]),
 array([[ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])]

In [141]:
np.vsplit(a,[1])


[array([[1, 2, 3, 4]]),
 array([[ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])]

In [142]:
np.split(a,[1,2],axis=0)

[array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]]), array([[ 9, 10, 11, 12]])]

In [143]:
np.vsplit(a,[1,2])

[array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]]), array([[ 9, 10, 11, 12]])]

In [144]:
np.split(a,[1,2],axis=1)

[array([[1],
        [5],
        [9]]),
 array([[ 2],
        [ 6],
        [10]]),
 array([[ 3,  4],
        [ 7,  8],
        [11, 12]])]

In [145]:
np.hsplit(a,[1,2])

[array([[1],
        [5],
        [9]]),
 array([[ 2],
        [ 6],
        [10]]),
 array([[ 3,  4],
        [ 7,  8],
        [11, 12]])]

In [146]:
np.hsplit(a,2)

[array([[ 1,  2],
        [ 5,  6],
        [ 9, 10]]),
 array([[ 3,  4],
        [ 7,  8],
        [11, 12]])]

### Merging Arrays

In [147]:
a=np.arange(1,5)
b=np.arange(5,9)
a,b

(array([1, 2, 3, 4]), array([5, 6, 7, 8]))

In [148]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [149]:
np.vstack((a,b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [150]:
np.vstack((b,a))

array([[5, 6, 7, 8],
       [1, 2, 3, 4]])

In [151]:
a=np.arange(1,5).reshape((1,4))
b=np.arange(5,9).reshape((1,4))
a,b

(array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]]))

In [152]:
np.vstack((a,b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [153]:
np.hstack((a,b))

array([[1, 2, 3, 4, 5, 6, 7, 8]])

In [155]:
a=np.arange(1,13).reshape((3,4))
b=np.arange(13,25).reshape((3,4))
a,b

(array([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]),
 array([[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]))

In [156]:
np.vstack((a,b))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [157]:
np.hstack((a,b))

array([[ 1,  2,  3,  4, 13, 14, 15, 16],
       [ 5,  6,  7,  8, 17, 18, 19, 20],
       [ 9, 10, 11, 12, 21, 22, 23, 24]])

In [158]:
a=np.arange(1,13).reshape((4,3))
b=np.arange(13,25).reshape((3,4))
a,b

(array([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]]),
 array([[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]))

In [159]:
np.vstack((a,b))

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 3 and the array at index 1 has size 4

In [160]:
np.hstack((a,b))

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 4 and the array at index 1 has size 3

In [161]:
a=np.arange(1,13).reshape((3,4))
b=np.arange(5,9)
a,b

(array([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]),
 array([5, 6, 7, 8]))

In [162]:
np.hstack((a,b))

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [163]:
np.vstack((a,b))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 5,  6,  7,  8]])

In [164]:
a=np.arange(1,13).reshape((3,4))
b=np.arange(5,9).reshape((1,4))
a,b

(array([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]),
 array([[5, 6, 7, 8]]))

In [165]:
np.vstack((a,b))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 5,  6,  7,  8]])

In [166]:
np.hstack((a,b))

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 3 and the array at index 1 has size 1